/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.io.BufferedInputStream;
import java.io.InputStream;
import javax.sound.sampled.*;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ulrich
 */
public class TcSound extends javax.swing.JFrame {

    /**
     * Creates new form TcSound
     */
    public TcSound() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        panelJoe = new javax.swing.JPanel();
        BIDDE = new javax.swing.JButton();
        bidde = new javax.swing.JButton();
        revert = new javax.swing.JButton();
        rewe = new javax.swing.JButton();
        ballad7 = new javax.swing.JButton();
        weisst = new javax.swing.JButton();
        konverter = new javax.swing.JButton();
        dasist = new javax.swing.JButton();
        eehm = new javax.swing.JButton();
        annee = new javax.swing.JButton();
        domaene = new javax.swing.JButton();
        kaffee = new javax.swing.JButton();
        panelPulp = new javax.swing.JPanel();
        wasjetzt = new javax.swing.JButton();
        ansteht = new javax.swing.JButton();
        was = new javax.swing.JButton();
        konzept = new javax.swing.JButton();
        butch = new javax.swing.JButton();
        neinmann = new javax.swing.JButton();
        panelMisc = new javax.swing.JPanel();
        bieker = new javax.swing.JButton();
        ballad = new javax.swing.JButton();
        jeopardy = new javax.swing.JButton();
        delate = new javax.swing.JButton();
        remoot = new javax.swing.JButton();
        snapshoot = new javax.swing.JButton();
        khan = new javax.swing.JButton();
        geil = new javax.swing.JButton();
        gescheitertA = new javax.swing.JButton();
        konzept2 = new javax.swing.JButton();
        essort = new javax.swing.JButton();
        konzept3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        standup = new javax.swing.JButton();
        cubage = new javax.swing.JButton();
        oey = new javax.swing.JButton();
        alarm = new javax.swing.JButton();
        listener = new javax.swing.JButton();
        meister = new javax.swing.JButton();
        standup1 = new javax.swing.JButton();
        standup2 = new javax.swing.JButton();
        standup3 = new javax.swing.JButton();
        standup4 = new javax.swing.JButton();
        standup5 = new javax.swing.JButton();
        standup6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Panel");
        setAlwaysOnTop(true);
        setIconImage(new ImageIcon("icon.jpg").getImage());
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));

        panel.setBackground(new java.awt.Color(51, 51, 51));
        panel.setLayout(null);

        panelJoe.setBackground(new java.awt.Color(51, 51, 51));
        panelJoe.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Joe Hanson", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(204, 204, 204)));
        panelJoe.setLayout(null);

        BIDDE.setText("BIDDE?");
        BIDDE.setActionCommand("bidde_fragend");
        BIDDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelJoe.add(BIDDE);
        BIDDE.setBounds(10, 20, 100, 29);

        bidde.setText("bidde?");
        bidde.setActionCommand("bidde_veraengstigt");
        bidde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelJoe.add(bidde);
        bidde.setBounds(110, 20, 100, 29);

        revert.setText("Reewert");
        revert.setActionCommand("reewert");
        revert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelJoe.add(revert);
        revert.setBounds(210, 20, 100, 29);

        rewe.setText("Rewe");
        rewe.setActionCommand("rewe");
        rewe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelJoe.add(rewe);
        rewe.setBounds(310, 20, 100, 29);

        ballad7.setText("So nicht");
        ballad7.setActionCommand("sonicht");
        ballad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelJoe.add(ballad7);
        ballad7.setBounds(110, 50, 100, 29);

        weisst.setText("Weisst Dus");
        weisst.setActionCommand("weisstdus");
        weisst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelJoe.add(weisst);
        weisst.setBounds(210, 50, 100, 29);

        konverter.setText("Konverter");
        konverter.setActionCommand("konverter");
        konverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelJoe.add(konverter);
        konverter.setBounds(310, 50, 100, 29);

        dasist.setText("Das ist das");
        dasist.setActionCommand("dasist");
        dasist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelJoe.add(dasist);
        dasist.setBounds(410, 20, 100, 29);

        eehm.setText("Eehm");
        eehm.setActionCommand("eehm");
        eehm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelJoe.add(eehm);
        eehm.setBounds(510, 20, 100, 29);

        annee.setText("Annee");
        annee.setActionCommand("aneene");
        annee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelJoe.add(annee);
        annee.setBounds(510, 50, 100, 29);

        domaene.setText("Domäne");
        domaene.setActionCommand("domaene");
        domaene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelJoe.add(domaene);
        domaene.setBounds(10, 50, 100, 29);

        kaffee.setText("Kaffee");
        kaffee.setActionCommand("kaffee");
        kaffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelJoe.add(kaffee);
        kaffee.setBounds(410, 50, 100, 29);

        panel.add(panelJoe);
        panelJoe.setBounds(20, 290, 620, 90);

        panelPulp.setBackground(new java.awt.Color(51, 51, 51));
        panelPulp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pulp Fiction", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(204, 204, 204)));
        panelPulp.setLayout(null);

        wasjetzt.setText("Was jetzt?");
        wasjetzt.setActionCommand("wasjetzt");
        wasjetzt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelPulp.add(wasjetzt);
        wasjetzt.setBounds(10, 20, 100, 29);

        ansteht.setText("Ich sag dir");
        ansteht.setActionCommand("ansteht");
        ansteht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelPulp.add(ansteht);
        ansteht.setBounds(110, 20, 100, 29);

        was.setText("1 mal was");
        was.setActionCommand("was");
        was.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelPulp.add(was);
        was.setBounds(210, 20, 100, 29);

        konzept.setText("Konzept");
        konzept.setActionCommand("konzept");
        konzept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelPulp.add(konzept);
        konzept.setBounds(310, 20, 100, 29);

        butch.setText("Zur Seite");
        butch.setActionCommand("butch");
        butch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelPulp.add(butch);
        butch.setBounds(410, 20, 100, 29);

        neinmann.setText("Nein Mann");
        neinmann.setActionCommand("neinmann");
        neinmann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelPulp.add(neinmann);
        neinmann.setBounds(510, 20, 100, 29);

        panel.add(panelPulp);
        panelPulp.setBounds(20, 20, 620, 60);

        panelMisc.setBackground(new java.awt.Color(51, 51, 51));
        panelMisc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Misc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(204, 204, 204)));
        panelMisc.setLayout(null);

        bieker.setText("Bieker");
        bieker.setActionCommand("bieker");
        bieker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelMisc.add(bieker);
        bieker.setBounds(10, 20, 100, 29);

        ballad.setText("Ballad");
        ballad.setActionCommand("ballad");
        ballad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelMisc.add(ballad);
        ballad.setBounds(110, 20, 100, 29);

        jeopardy.setText("Jeopardy");
        jeopardy.setActionCommand("jeopardy");
        jeopardy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelMisc.add(jeopardy);
        jeopardy.setBounds(210, 20, 100, 29);

        delate.setText("Delete");
        delate.setActionCommand("delate");
        delate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelMisc.add(delate);
        delate.setBounds(410, 20, 100, 29);

        remoot.setText("Remote");
        remoot.setActionCommand("remoot");
        remoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelMisc.add(remoot);
        remoot.setBounds(310, 20, 100, 29);

        snapshoot.setText("Snapshoot");
        snapshoot.setActionCommand("snapshoot");
        snapshoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelMisc.add(snapshoot);
        snapshoot.setBounds(510, 20, 100, 29);

        khan.setText("Khan");
        khan.setActionCommand("khan");
        khan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelMisc.add(khan);
        khan.setBounds(10, 50, 100, 29);

        geil.setText("Wie geil");
        geil.setActionCommand("geil");
        geil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelMisc.add(geil);
        geil.setBounds(210, 50, 100, 29);

        gescheitertA.setText("Fail");
        gescheitertA.setActionCommand("gesch_reiner");
        gescheitertA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelMisc.add(gescheitertA);
        gescheitertA.setBounds(310, 50, 100, 29);

        konzept2.setText("Quiet!");
        konzept2.setActionCommand("quiet");
        konzept2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelMisc.add(konzept2);
        konzept2.setBounds(510, 50, 100, 29);

        essort.setText("Essort");
        essort.setActionCommand("essort");
        essort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelMisc.add(essort);
        essort.setBounds(110, 50, 100, 29);

        konzept3.setText("Fail Satanic");
        konzept3.setActionCommand("gescheitert_satan");
        konzept3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        panelMisc.add(konzept3);
        konzept3.setBounds(410, 50, 100, 29);

        panel.add(panelMisc);
        panelMisc.setBounds(20, 190, 620, 90);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bastelecke", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(204, 204, 204)));
        jPanel5.setLayout(null);

        standup.setText("Stand up");
        standup.setActionCommand("standup");
        standup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        jPanel5.add(standup);
        standup.setBounds(10, 20, 99, 29);

        cubage.setText("Cubage");
        cubage.setActionCommand("qbitch");
        cubage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        jPanel5.add(cubage);
        cubage.setBounds(110, 20, 100, 29);

        oey.setText("Öeeey");
        oey.setActionCommand("oey");
        oey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        jPanel5.add(oey);
        oey.setBounds(310, 20, 100, 29);

        alarm.setText("Alarm");
        alarm.setActionCommand("alarm");
        alarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        jPanel5.add(alarm);
        alarm.setBounds(210, 20, 100, 29);

        listener.setText("Listener");
        listener.setActionCommand("lauschangriff");
        listener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        jPanel5.add(listener);
        listener.setBounds(410, 20, 100, 29);

        meister.setText(" The Fog");
        meister.setActionCommand("fog");
        meister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        jPanel5.add(meister);
        meister.setBounds(510, 20, 100, 29);

        standup1.setText("HorHorHor");
        standup1.setActionCommand("kevin");
        standup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        jPanel5.add(standup1);
        standup1.setBounds(510, 50, 99, 29);

        standup2.setText("Danköö");
        standup2.setActionCommand("dankoe");
        standup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        jPanel5.add(standup2);
        standup2.setBounds(110, 50, 99, 29);

        standup3.setText("Falsch");
        standup3.setActionCommand("falsch");
        standup3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        jPanel5.add(standup3);
        standup3.setBounds(10, 50, 99, 29);

        standup4.setText("Schafskäse");
        standup4.setActionCommand("schafskaese");
        standup4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        jPanel5.add(standup4);
        standup4.setBounds(210, 50, 99, 29);

        standup5.setText("Bäm!");
        standup5.setActionCommand("baehm");
        standup5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        jPanel5.add(standup5);
        standup5.setBounds(310, 50, 99, 29);

        standup6.setText("Erbärmlich");
        standup6.setActionCommand("erbaermlich");
        standup6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSound(evt);
            }
        });
        jPanel5.add(standup6);
        standup6.setBounds(410, 50, 99, 29);

        panel.add(jPanel5);
        jPanel5.setBounds(20, 90, 620, 90);

        getContentPane().add(panel, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-680)/2, (screenSize.height-443)/2, 680, 443);
    }// </editor-fold>//GEN-END:initComponents

    private void playSound(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playSound
        try {

            // generate filename from action command
            String command = ((JButton) evt.getSource()).getActionCommand();
            String fileName = command.concat(".wav");

            // Open an audio input stream.
            InputStream inputStream = this.getClass().getResourceAsStream(fileName);
            InputStream bufferedInputStream = new BufferedInputStream(inputStream);
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(bufferedInputStream);


            // Open audio clip and load samples from the audio input stream.
            Clip clip = AudioSystem.getClip();
            clip.open(audioStream);
            clip.start();

            inputStream.close();
            bufferedInputStream.close();

        } catch (Exception exc) {
            System.out.println(exc.toString());
            JOptionPane.showMessageDialog(null, exc.getMessage());
        }
    }//GEN-LAST:event_playSound

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TcSound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TcSound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TcSound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TcSound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                JFrame frame = new TcSound();
                frame.setIconImage(new ImageIcon(TcSound.class.getResource("icon.png")).getImage());
                frame.setVisible(true);


            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BIDDE;
    private javax.swing.JButton alarm;
    private javax.swing.JButton annee;
    private javax.swing.JButton ansteht;
    private javax.swing.JButton ballad;
    private javax.swing.JButton ballad7;
    private javax.swing.JButton bidde;
    private javax.swing.JButton bieker;
    private javax.swing.JButton butch;
    private javax.swing.JButton cubage;
    private javax.swing.JButton dasist;
    private javax.swing.JButton delate;
    private javax.swing.JButton domaene;
    private javax.swing.JButton eehm;
    private javax.swing.JButton essort;
    private javax.swing.JButton geil;
    private javax.swing.JButton gescheitertA;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jeopardy;
    private javax.swing.JButton kaffee;
    private javax.swing.JButton khan;
    private javax.swing.JButton konverter;
    private javax.swing.JButton konzept;
    private javax.swing.JButton konzept2;
    private javax.swing.JButton konzept3;
    private javax.swing.JButton listener;
    private javax.swing.JButton meister;
    private javax.swing.JButton neinmann;
    private javax.swing.JButton oey;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelJoe;
    private javax.swing.JPanel panelMisc;
    private javax.swing.JPanel panelPulp;
    private javax.swing.JButton remoot;
    private javax.swing.JButton revert;
    private javax.swing.JButton rewe;
    private javax.swing.JButton snapshoot;
    private javax.swing.JButton standup;
    private javax.swing.JButton standup1;
    private javax.swing.JButton standup2;
    private javax.swing.JButton standup3;
    private javax.swing.JButton standup4;
    private javax.swing.JButton standup5;
    private javax.swing.JButton standup6;
    private javax.swing.JButton was;
    private javax.swing.JButton wasjetzt;
    private javax.swing.JButton weisst;
    // End of variables declaration//GEN-END:variables
}
